#!/bin/sh

echo "... ... Starting Service rsyslogd ... ..."

# Close STDOUT file descriptor
exec 1<&-
# Close STDERR FD
exec 2<&-

# Open STDOUT as a file for read and write.
exec 1<>/var/log/runsvdir/rsyslogd.log

# Redirect STDERR to STDOUT
exec 2>&1

echo "Startup log of the command line: exec rsyslogd -n"
echo "............................................................................................."

[ -r /etc/envvars ] && . /etc/envvars

[ -f /etc/rsyslog.conf ] && sed  -i "s|.*$ModLoad imklog.so.*|###imklog.so removed###|g" /etc/rsyslog.conf
exec rsyslogd -n
