#!/usr/bin/env /bin/sh

set -e

[ -r /etc/envvars ] && . /etc/envvars
fn=$(basename $0)
#echo "\$_:$_   \$0:$0   \$-:$-   \$@:$@"
servicename="01-go-dnsmasq"
#####################################################################################################
echo "$fn:Enabling go-dnsmasq service, by symlinking /etc/services.d/${servicename} to /etc/service"
ln -s /etc/services.d/${servicename} /etc/service/
#####################################################################################################
CONTAINER_HOST=$(cat /etc/hostname)
if [ -z "${CONTAINER_HOST}" ]; then
    echo "Failed to get hostname, aborting" >&2
    exit 1
fi

CONTAINER_IP=$(prvip)

if [ -z "${CONTAINER_IP}" ]; then
    echo "Failed to get IP address, aborting" >&2
    exit 2
fi

echo "$fn:Prepared CONTAINER_HOST:${CONTAINER_HOST} and CONTAINER_IP:${CONTAINER_IP} for go-dnsmasq ... ..."

export CONTAINER_HOST
export CONTAINER_IP

export > /etc/envvars

unset fn servicename
