#!/bin/sh
set -e
# Reset PATH to avoid messed up duplication
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Close STDOUT file descriptor
exec 1<&-
# Close STDERR FD
exec 2<&-

# Open STDOUT as a file for read and write.
exec 1<>/var/log/runsvdir/runsvdir.log

# Redirect STDERR to STDOUT
exec 2>&1

[ -r /etc/envvars ] && . /etc/envvars

exec env - PATH=${PATH} \
runsvdir -P /etc/service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
