#!/bin/sh
set -e

#PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

exec 2>&1

LAST=0
test -x /etc/runit/reboot && LAST=6

echo "Forcing all services in /etc/service to stop ... ..."
# First try to stop services by the reverse order
for _srv in $(ls -r1 /etc/service); do
    sv force-stop ${_srv}
done
# Then force stop all service if there any remains
sv -w196 force-stop /etc/service/* 2>/dev/null

echo "Running post-service clearing scripts in /etc/postclr.d"
for _script in /etc/postclr.d/*; do
    if [ -x ${_script} ]; then
        echo >&2 "*** Running: ${_script}"
        ${_script}
    else
        echo >&2 "*** Failed to run: ${_script}. Please chmod +x ${_script}"
    fi
done

\rm -f /etc/runit/stopall
test -x /etc/init.d/rc && /etc/init.d/rc ${LAST}

unset _script _srv
