#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "GLIBC_VERSION=.*" $(pwd)/Dockerfile | tr -d GLIBC_VERSION=v | tr -d . | tr -d - | tr -d '[:space:]')
sudo docker build --force-rm --tag "${hubid}/apglibc:${tag}" .
sudo docker tag "${hubid}/apglibc:${tag}" "${hubid}/apglibc:latest"
